# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Project6_test/Project6_test/Project6_test.runs/synth_1/.Xil/Vivado-10880-C195-UL-41/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8c62/hdl
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/c923
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_slv_0_0/src/blk_mem_gen_0_1
  } {
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8c62/hdl
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/c923
    c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_slv_0_0/src/blk_mem_gen_0_1
  } {
      C:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/synth/design_1_processing_system7_0_0.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/synth/design_1_xbar_0.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v
      C:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/synth/design_1.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/synth/design_1_auto_pc_0.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/d072/hdl/kybd_slv_v1_0_S00_AXI.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/d072/hdl/kybd_slv_v1_0.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_kybd_slv_0_1/synth/design_1_kybd_slv_0_1.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/bc0d/src/ascii_writer.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/bc0d/src/char8x12_lookup_table.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/bc0d/hdl/slv_v1_0_S00_AXI.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/bc0d/src/vga_sync.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/bc0d/hdl/slv_v1_0.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_slv_0_0/synth/design_1_slv_0_0.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_slv_0_0/src/blk_mem_gen_0_1/synth/blk_mem_gen_0.vhd
      c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/synth/design_1_rst_ps7_0_50M_0.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_3 c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ip/design_1_slv_0_0/src/blk_mem_gen_0_1/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_4 c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/1f5a/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 c:/Project6_test/Project6_test/Project6_test.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Project6_test/Project6_test/Project6_test.runs/synth_1/.Xil/Vivado-10880-C195-UL-41/realtime/design_1_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Project6_test/Project6_test/Project6_test.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Project6_test/Project6_test/Project6_test.runs/synth_1/.Xil/Vivado-10880-C195-UL-41/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
